name: Luma CI Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  run-test:
    name: 'Run tests'
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres

        env:
          POSTGRES_PASSWORD: root
          POSTGRES_USER: admin
          POSTGRES_DB: test

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - run: |
          sudo apt-get update && sudo apt-get install --yes --no-install-recommends postgresql-client
        env:
          PGPASSWORD: root

      - name: Git clone
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          cache: 'maven'

      - name: Cache maven
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Install Playwright
        run: mvn exec:java -e -D exec.mainClass=com.microsoft.playwright.CLI -D exec.args="install --with-deps"

      - name: Maven test
        run: mvn -e test
        env:
          BROWSER_OPTIONS: |
            browserType=chromium;
            screenWidth=1366;
            screenHeight=768;
            isHeadless=true;
            slowMo=2000;
            tracing=true;
            video=true
          CHROME_OPTIONS: |
            --disable-gpu;
            --no-sandbox;
            --disable-dev-shm-usage;
            --headless;
            --window-size=1920,1080;
            --disable-web-security;
            --allow-running-insecure-content;
            --ignore-certificate-errors
          CI_RUN: true

      - name: Attach screenshots and reports
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: screenshots-and-report
          path: |
            screenshots
            **/surefire-reports/emailable-report.html
            tracing/
            video/

      - name: Test Reporter
        uses: dorny/test-reporter@v1.8.0
        if: success() || failure()
        with:
          name: Luma Project Test Report
          path: target/surefire-reports/TEST-*.xml
          reporter: java-junit

      - name: Clean up gh-pages branch (optional)
        run: |
          git checkout -f gh-pages
          git rm -rf .

      - name: Get Allure history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure Report action
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: target/allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          personal_token: ${{ secrets.TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history

  check-java-code-style:
    name: Check Java code style

    runs-on: ubuntu-latest

    steps:
      - name: Clone code from repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run java checkstyle
        uses: nikitasavinov/checkstyle-action@0.6.0
